#!/bin/bash

## App Name
AppName='pool_test'

## Compiler
CC='g++'

## Defines
Defines='-D__DEBUG'

## Flags
Flags='-O3'

## Libs
Libs='-lpthread'

## Source files
SRCFiles=`find -not -path '*windows*' -regex '.*/.*\.\(c\|cpp\|h\)$' -print0 | xargs -0`

## Compile
eval "$CC $Flags -o $AppName $Defines $Libs $SRCFiles"
